# Aggregation
menggabungkan beberapa feature untuk melihat insight apa yang bisa didapatkan

In [161]:
import pandas as pd

In [162]:
df = pd.read_csv('Data/hotel_bookings.csv')
df['country'] = df['country'].fillna('Unknown') 
df['children'] = df['children'].fillna(0)
df['agent'] = df['agent'].fillna(0)
df.drop(columns=['company'], axis=1, inplace=True)
df.drop_duplicates(inplace=True)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

### .groupby()
Menggabungkan beberapa feature yang berkolerasi

------------------

##### .value_counts()
Mengitung jumlah

In [163]:
# hotel & is_canceled -- Hotel mana aja yang di canceled
df.groupby('hotel')['is_canceled'].value_counts().unstack()

is_canceled       0      1
hotel
City Hotel    37377  16049
Resort Hotel  25987   7976

In [164]:
# adr = average daily rate -- Mencari harga rata rata pada hotel
df.groupby('hotel')['adr'].mean()

hotel
City Hotel      110.985270
Resort Hotel     99.030296
Name: adr, dtype: float64

In [165]:
# Harga rata rata hotel per tahun
df.groupby(['arrival_date_year','hotel'])['adr'].mean().unstack()

hotel              City Hotel  Resort Hotel
arrival_date_year
2015                89.813927     94.450802
2016               107.896446     90.653587
2017               121.986516    113.020094

#### .agg()
.agg() (aggregate) adalah untuk melakukan satu atau beberapa operasi agregasi pada data

In [166]:
# Jumlah hari pemesanan setiap tamu
df.groupby('customer_type')['lead_time'].agg(['min', 'max', 'mean', 'count'])

                 min  max        mean  count
customer_type
Contract           0  532  109.225231   3139
Group              0  468   51.584559    544
Transient          0  737   73.431274  71982
Transient-Party    0  542  113.057489  11724