# Feature Engineering
Membuat atau memodifikasi feature agar model machine learning bisa bekerja lebih baik

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('Data/hotel_bookings.csv')
df['country'] = df['country'].fillna('Unknown') 
df['children'] = df['children'].fillna(0)
df['agent'] = df['agent'].fillna(0)
df.drop(columns=['company'], axis=1, inplace=True)
df.drop_duplicates(inplace=True)
df

In [8]:
# Total malam setiap minggu
df['total_nights'] = df['stays_in_week_nights']+ df['stays_in_weekend_nights']

In [9]:
df[['total_nights', 'stays_in_week_nights', 'stays_in_weekend_nights']].sample(10)

        total_nights  stays_in_week_nights  stays_in_weekend_nights
11427              3                     1                        2
20223              2                     2                        0
64392              4                     4                        0
109172             3                     3                        0
102937             2                     2                        0
50746              1                     1                        0
62209              9                     7                        2
39248              2                     2                        0
95888              2                     1                        1
89622              1                     0                        1

In [10]:
df['customers'] = df['adults'] + df['children'] + df['babies']
df[['customers', 'adults', 'children', 'babies']].sample(10)

        customers  adults  children  babies
7473          2.0       2       0.0       0
55869         2.0       2       0.0       0
71853         2.0       2       0.0       0
5224          2.0       2       0.0       0
71330         2.0       2       0.0       0
117924        2.0       2       0.0       0
114065        2.0       2       0.0       0
118302        3.0       2       1.0       0
107828        2.0       2       0.0       0
58331         2.0       2       0.0       0

#### .apply()
Menerapkan sebuah fungsi ke setiap elemen, baris, atau kolom

---------------------

##### lambda x == def
fungsi anonim singkat yang sering dipakai di apply()

In [11]:
# Mengubah 0 & 1 menjadi No & Yes
df['is_repeated_category'] = df['is_repeated_guest'].apply(lambda x: 'Yes' if x == 1 else 'No' )

In [12]:
df[['is_repeated_category', 'is_repeated_guest']].sample(10)

       is_repeated_category  is_repeated_guest
101035                   No                  0
103472                   No                  0
13939                    No                  0
99106                    No                  0
48108                    No                  0
45960                    No                  0
16494                    No                  0
36088                    No                  0
110531                   No                  0
102450                   No                  0

### Ubah tipe data object -> date time
Kenapa harus di kanan dan kiri, agar tidak membuat kolom baru hanya mengganti kolom yang dibuah

In [13]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

In [14]:
df['reservation_status_date']

0        2015-07-01
1        2015-07-01
2        2015-07-02
3        2015-07-02
4        2015-07-03
            ...
119385   2017-09-06
119386   2017-09-07
119387   2017-09-07
119388   2017-09-07
119389   2017-09-07
Name: reservation_status_date, Length: 87389, dtype: datetime64[ns]

#### .map()
digunakan untuk memetakan (mapping) nilai lama menjadi nilai baru berdasarkan:
- dictionary
- fungsi
- lambda

#### (Boolean) -> lambda 
#### (Multiclass) -> map

In [15]:
# Mengubah nama bulan menjadi angka
month_mapping = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

df['arrival_date_month'] = df['arrival_date_month'].map(month_mapping)

In [16]:
df['arrival_date_month']

0         7
1         7
2         7
3         7
4         7
         ..
119385    8
119386    8
119387    8
119388    8
119389    8
Name: arrival_date_month, Length: 87389, dtype: int64